# Tratamento dos dados de óbitos

In [1]:
import pandas as pd
import numpy as np

---
# 2019

In [29]:
# Importando os dados Brutos de 2019

df_2019_1 = pd.read_csv('C:\\Users\\jobsr\\OneDrive\\Documentos\\GitHub\\ProjetoIntegradorIII\\DATASUS\\Obitos_Procedimento_Municipio\\Brutos\\2019_1_O.csv', sep=';', encoding='latin-1')
df_2019_2 = pd.read_csv('C:\\Users\\jobsr\\OneDrive\\Documentos\\GitHub\\ProjetoIntegradorIII\\DATASUS\\Obitos_Procedimento_Municipio\\Brutos\\2019_2_O.csv', sep=';', encoding='latin-1')
df_2019_3 = pd.read_csv('C:\\Users\\jobsr\\OneDrive\\Documentos\\GitHub\\ProjetoIntegradorIII\\DATASUS\\Obitos_Procedimento_Municipio\\Brutos\\2019_3_O.csv', sep=';', encoding='latin-1')
df_2019_4 = pd.read_csv('C:\\Users\\jobsr\\OneDrive\\Documentos\\GitHub\\ProjetoIntegradorIII\\DATASUS\\Obitos_Procedimento_Municipio\\Brutos\\2019_4_O.csv', sep=';', encoding='latin-1')

In [30]:
# Drop das colunas "Acompanhamento_Intercorrencias_Pre_Pos_Transplante" e "Total"
df_2019_1.drop(columns=['Acompanhamento_Intercorrencias_Pre_Pos_Transplante', 'Total'], inplace=True)
df_2019_2.drop(columns=['Acompanhamento_Intercorrencias_Pre_Pos_Transplante', 'Total'], inplace=True)
df_2019_3.drop(columns=['Acompanhamento_Intercorrencias_Pre_Pos_Transplante', 'Total'], inplace=True)
df_2019_4.drop(columns=['Acompanhamento_Intercorrencias_Pre_Pos_Transplante', 'Total'], inplace=True)


# Gerar uma nova coluna com o ano e o trimestre para cada tabela de 2019
df_2019_1['Ano'] = 2019
df_2019_1['Trimestre'] = 1

df_2019_2['Ano'] = 2019
df_2019_2['Trimestre'] = 2

df_2019_3['Ano'] = 2019
df_2019_3['Trimestre'] = 3

df_2019_4['Ano'] = 2019
df_2019_4['Trimestre'] = 4


# Gerar um código primário unindo as colunas Ano, Trimestre, Código do Município. Essa coluna será usada como chave primária para mesclar as tabelas. Criar uma nova coluna com o nome "UID"
df_2019_1['UID'] = df_2019_1['Ano'].astype(str) + df_2019_1['Trimestre'].astype(str) + df_2019_1['Codigo_Municipio'].astype(str)
df_2019_2['UID'] = df_2019_2['Ano'].astype(str) + df_2019_2['Trimestre'].astype(str) + df_2019_2['Codigo_Municipio'].astype(str)
df_2019_3['UID'] = df_2019_3['Ano'].astype(str) + df_2019_3['Trimestre'].astype(str) + df_2019_3['Codigo_Municipio'].astype(str)
df_2019_4['UID'] = df_2019_4['Ano'].astype(str) + df_2019_4['Trimestre'].astype(str) + df_2019_4['Codigo_Municipio'].astype(str)



# Mesclar as tabelas em uma única tabela
df_2019 = pd.concat([df_2019_1, df_2019_2, df_2019_3, df_2019_4], ignore_index=True)

# Mover as três últimas colunas para o início da tabela concatenada do ano
cols = df_2019.columns.tolist()
cols = cols[-3:] + cols[:-3]
df_2019 = df_2019[cols]

# Salvar a tabela concatenada em um arquivo csv
df_2019.to_csv('C:\\Users\\jobsr\\OneDrive\\Documentos\\GitHub\\ProjetoIntegradorIII\\DATASUS\\Obitos_Procedimento_Municipio\\Tratados\\Obitos_2019.csv', index=False, sep=';', encoding='latin-1')

In [28]:
df_2019.head()

,Ano,Trimestre,UID,Codigo_Municipio,Municipio,Coleta_Material,Diagnostico_Endoscopia,Metodos_Diagnosticos_Especialidades,Consultas_Atendimentos_Acompanhamentos,Tratamentos_Clinicos_Outras_Especialidades,...,Cirurgia_Aparelho_Geniturinario,Cirugia_Mama,Cirurgia_Obstetrica,Cirurgia_Toracica,Cirurgia_Reparadora,Bucomaxilofacial,Outras_Cirurgias,Cirurgia_Oncologia,Processamento_Tecidos_Transplante,Transplante_Orgaos_Tecidos_Celulas
0,2019,1,20191110001,110001,ALTA FLORESTA D'OESTE,0,0,0,0,12,...,0,0,0,0,0,0,1,0,0,0
1,2019,1,20191110002,110002,ARIQUEMES,0,0,0,0,28,...,0,0,0,1,0,0,3,0,0,0
2,2019,1,20191110003,110003,CABIXI,0,0,0,0,3,...,0,0,0,0,1,0,0,0,0,0
3,2019,1,20191110004,110004,CACOAL,0,0,0,0,37,...,0,0,0,1,0,0,6,0,0,0
4,2019,1,20191110005,110005,CEREJEIRAS,0,0,0,0,6,...,1,0,0,0,0,0,0,0,0,0

---
# 2020

In [13]:
# Importando os dados Brutos de 2020

df_2020_1 = pd.read_csv('C:\\Users\\jobsr\\OneDrive\\Documentos\\GitHub\\ProjetoIntegradorIII\\DATASUS\\Obitos_Procedimento_Municipio\\Brutos\\2020_1_O.csv', sep=';', encoding='latin-1')
df_2020_2 = pd.read_csv('C:\\Users\\jobsr\\OneDrive\\Documentos\\GitHub\\ProjetoIntegradorIII\\DATASUS\\Obitos_Procedimento_Municipio\\Brutos\\2020_2_O.csv', sep=';', encoding='latin-1')
df_2020_3 = pd.read_csv('C:\\Users\\jobsr\\OneDrive\\Documentos\\GitHub\\ProjetoIntegradorIII\\DATASUS\\Obitos_Procedimento_Municipio\\Brutos\\2020_3_O.csv', sep=';', encoding='latin-1')
df_2020_4 = pd.read_csv('C:\\Users\\jobsr\\OneDrive\\Documentos\\GitHub\\ProjetoIntegradorIII\\DATASUS\\Obitos_Procedimento_Municipio\\Brutos\\2020_4_O.csv', sep=';', encoding='latin-1')

In [31]:
# Drop das colunas "Acompanhamento_Intercorrencias_Pre_Pos_Transplante" e "Total"
df_2020_1.drop(columns=['Acompanhamento_Intercorrencias_Pre_Pos_Transplante', 'Total'], inplace=True)
df_2020_2.drop(columns=['Acompanhamento_Intercorrencias_Pre_Pos_Transplante', 'Total'], inplace=True)
df_2020_3.drop(columns=['Acompanhamento_Intercorrencias_Pre_Pos_Transplante', 'Total'], inplace=True)
df_2020_4.drop(columns=['Acompanhamento_Intercorrencias_Pre_Pos_Transplante', 'Total'], inplace=True)

# Gerar uma nova coluna com o ano e o trimestre para cada tabela de 2020
df_2020_1['Ano'] = 2020
df_2020_1['Trimestre'] = 1

df_2020_2['Ano'] = 2020
df_2020_2['Trimestre'] = 2

df_2020_3['Ano'] = 2020
df_2020_3['Trimestre'] = 3

df_2020_4['Ano'] = 2020
df_2020_4['Trimestre'] = 4

# Gerar um código primário unindo as colunas Ano, Trimestre, Código do Município. Essa coluna será usada como chave primária para mesclar as tabelas. Criar uma nova coluna com o nome "UID"
df_2020_1['UID'] = df_2020_1['Ano'].astype(str) + df_2020_1['Trimestre'].astype(str) + df_2020_1['Codigo_Municipio'].astype(str)
df_2020_2['UID'] = df_2020_2['Ano'].astype(str) + df_2020_2['Trimestre'].astype(str) + df_2020_2['Codigo_Municipio'].astype(str)
df_2020_3['UID'] = df_2020_3['Ano'].astype(str) + df_2020_3['Trimestre'].astype(str) + df_2020_3['Codigo_Municipio'].astype(str)
df_2020_4['UID'] = df_2020_4['Ano'].astype(str) + df_2020_4['Trimestre'].astype(str) + df_2020_4['Codigo_Municipio'].astype(str)

# Mesclar as tabelas em uma única tabela
df_2020 = pd.concat([df_2020_1, df_2020_2, df_2020_3, df_2020_4], ignore_index=True)

# Mover as três últimas colunas para o início da tabela concatenada do ano
cols = df_2020.columns.tolist()
cols = cols[-3:] + cols[:-3]
df_2020 = df_2020[cols]

# Salvar a tabela concatenada em um arquivo csv
df_2020.to_csv('C:\\Users\\jobsr\\OneDrive\\Documentos\\GitHub\\ProjetoIntegradorIII\\DATASUS\\Obitos_Procedimento_Municipio\\Tratados\\Obitos_2020.csv', index=False, sep=';', encoding='latin-1')

df_2020.head()

,Ano,Trimestre,UID,Codigo_Municipio,Municipio,Coleta_Material,Diagnostico_Endoscopia,Metodos_Diagnosticos_Especialidades,Consultas_Atendimentos_Acompanhamentos,Tratamentos_Clinicos_Outras_Especialidades,...,Cirurgia_Aparelho_Geniturinario,Cirugia_Mama,Cirurgia_Obstetrica,Cirurgia_Toracica,Cirurgia_Reparadora,Bucomaxilofacial,Outras_Cirurgias,Cirurgia_Oncologia,Processamento_Tecidos_Transplante,Transplante_Orgaos_Tecidos_Celulas
0,2020,1,20201110001,110001,ALTA FLORESTA D'OESTE,0,0,0,0,7,...,0,0,0,0,0,0,0,0,0,10.0
1,2020,1,20201110002,110002,ARIQUEMES,0,0,0,0,28,...,0,0,0,0,0,0,1,1,0,41.0
2,2020,1,20201110003,110003,CABIXI,0,0,0,0,2,...,0,0,0,0,0,0,0,0,0,2.0
3,2020,1,20201110004,110004,CACOAL,0,0,0,3,32,...,0,0,1,0,0,1,2,0,0,60.0
4,2020,1,20201110005,110005,CEREJEIRAS,0,0,0,0,4,...,0,0,0,0,0,0,0,0,0,5.0

---
# 2021

In [15]:
# Importando os dados Brutos de 2021

df_2021_1 = pd.read_csv('C:\\Users\\jobsr\\OneDrive\\Documentos\\GitHub\\ProjetoIntegradorIII\\DATASUS\\Obitos_Procedimento_Municipio\\Brutos\\2021_1_O.csv', sep=';', encoding='latin-1')
df_2021_2 = pd.read_csv('C:\\Users\\jobsr\\OneDrive\\Documentos\\GitHub\\ProjetoIntegradorIII\\DATASUS\\Obitos_Procedimento_Municipio\\Brutos\\2021_2_O.csv', sep=';', encoding='latin-1')
df_2021_3 = pd.read_csv('C:\\Users\\jobsr\\OneDrive\\Documentos\\GitHub\\ProjetoIntegradorIII\\DATASUS\\Obitos_Procedimento_Municipio\\Brutos\\2021_3_O.csv', sep=';', encoding='latin-1')
df_2021_4 = pd.read_csv('C:\\Users\\jobsr\\OneDrive\\Documentos\\GitHub\\ProjetoIntegradorIII\\DATASUS\\Obitos_Procedimento_Municipio\\Brutos\\2021_4_O.csv', sep=';', encoding='latin-1')

In [32]:
# Drop das colunas "Acompanhamento_Intercorrencias_Pre_Pos_Transplante" e "Total"
df_2021_1.drop(columns=['Acompanhamento_Intercorrencias_Pre_Pos_Transplante', 'Total'], inplace=True)
df_2021_2.drop(columns=['Acompanhamento_Intercorrencias_Pre_Pos_Transplante', 'Total'], inplace=True)
df_2021_3.drop(columns=['Acompanhamento_Intercorrencias_Pre_Pos_Transplante', 'Total'], inplace=True)
df_2021_4.drop(columns=['Acompanhamento_Intercorrencias_Pre_Pos_Transplante', 'Total'], inplace=True)

# Gerar uma nova coluna com o ano e o trimestre para cada tabela de 2021
df_2021_1['Ano'] = 2021
df_2021_1['Trimestre'] = 1

df_2021_2['Ano'] = 2021
df_2021_2['Trimestre'] = 2

df_2021_3['Ano'] = 2021
df_2021_3['Trimestre'] = 3

df_2021_4['Ano'] = 2021
df_2021_4['Trimestre'] = 4

# Gerar um código primário unindo as colunas Ano, Trimestre, Código do Município. Essa coluna será usada como chave primária para mesclar as tabelas. Criar uma nova coluna com o nome "UID"
df_2021_1['UID'] = df_2021_1['Ano'].astype(str) + df_2021_1['Trimestre'].astype(str) + df_2021_1['Codigo_Municipio'].astype(str)
df_2021_2['UID'] = df_2021_2['Ano'].astype(str) + df_2021_2['Trimestre'].astype(str) + df_2021_2['Codigo_Municipio'].astype(str)
df_2021_3['UID'] = df_2021_3['Ano'].astype(str) + df_2021_3['Trimestre'].astype(str) + df_2021_3['Codigo_Municipio'].astype(str)
df_2021_4['UID'] = df_2021_4['Ano'].astype(str) + df_2021_4['Trimestre'].astype(str) + df_2021_4['Codigo_Municipio'].astype(str)

# Mesclar as tabelas em uma única tabela
df_2021 = pd.concat([df_2021_1, df_2021_2, df_2021_3, df_2021_4], ignore_index=True)

# Mover as três últimas colunas para o início da tabela concatenada do ano
cols = df_2021.columns.tolist()
cols = cols[-3:] + cols[:-3]
df_2021 = df_2021[cols]

# Salvar a tabela concatenada em um arquivo csv
df_2021.to_csv('C:\\Users\\jobsr\\OneDrive\\Documentos\\GitHub\\ProjetoIntegradorIII\\DATASUS\\Obitos_Procedimento_Municipio\\Tratados\\Obitos_2021.csv', index=False, sep=';', encoding='latin-1')

df_2021.head()

,Ano,Trimestre,UID,Codigo_Municipio,Municipio,Coleta_Material,Diagnostico_Endoscopia,Metodos_Diagnosticos_Especialidades,Consultas_Atendimentos_Acompanhamentos,Tratamentos_Clinicos_Outras_Especialidades,...,Cirurgia_Aparelho_Geniturinario,Cirugia_Mama,Cirurgia_Obstetrica,Cirurgia_Toracica,Cirurgia_Reparadora,Bucomaxilofacial,Outras_Cirurgias,Cirurgia_Oncologia,Processamento_Tecidos_Transplante,Transplante_Orgaos_Tecidos_Celulas
0,2021,1,20211110001,110001,ALTA FLORESTA D'OESTE,0,0,0,0,18,...,0,0,0,0,0,0,0,0,0,0
1,2021,1,20211110002,110002,ARIQUEMES,0,0,0,0,208,...,0,0,0,0,0,0,1,0,0,1
2,2021,1,20211110003,110003,CABIXI,0,0,0,0,5,...,0,0,0,0,0,0,0,0,0,0
3,2021,1,20211110004,110004,CACOAL,0,0,0,1,31,...,0,0,0,0,0,0,1,0,0,0
4,2021,1,20211110005,110005,CEREJEIRAS,0,0,0,0,16,...,0,0,0,0,0,0,0,0,0,0

---
# 2022

In [17]:
# Importando os dados Brutos de 2022

df_2022_1 = pd.read_csv('C:\\Users\\jobsr\\OneDrive\\Documentos\\GitHub\\ProjetoIntegradorIII\\DATASUS\\Obitos_Procedimento_Municipio\\Brutos\\2022_1_O.csv', sep=';', encoding='latin-1')
df_2022_2 = pd.read_csv('C:\\Users\\jobsr\\OneDrive\\Documentos\\GitHub\\ProjetoIntegradorIII\\DATASUS\\Obitos_Procedimento_Municipio\\Brutos\\2022_2_O.csv', sep=';', encoding='latin-1')
df_2022_3 = pd.read_csv('C:\\Users\\jobsr\\OneDrive\\Documentos\\GitHub\\ProjetoIntegradorIII\\DATASUS\\Obitos_Procedimento_Municipio\\Brutos\\2022_3_O.csv', sep=';', encoding='latin-1')
df_2022_4 = pd.read_csv('C:\\Users\\jobsr\\OneDrive\\Documentos\\GitHub\\ProjetoIntegradorIII\\DATASUS\\Obitos_Procedimento_Municipio\\Brutos\\2022_4_O.csv', sep=';', encoding='latin-1')

In [33]:
# Drop das colunas "Acompanhamento_Intercorrencias_Pre_Pos_Transplante" e "Total"
df_2022_1.drop(columns=['Acompanhamento_Intercorrencias_Pre_Pos_Transplante', 'Total'], inplace=True)
df_2022_2.drop(columns=['Acompanhamento_Intercorrencias_Pre_Pos_Transplante', 'Total'], inplace=True)
df_2022_3.drop(columns=['Acompanhamento_Intercorrencias_Pre_Pos_Transplante', 'Total'], inplace=True)
df_2022_4.drop(columns=['Acompanhamento_Intercorrencias_Pre_Pos_Transplante', 'Total'], inplace=True)

# Gerar uma nova coluna com o ano e o trimestre para cada tabela de 2022
df_2022_1['Ano'] = 2022
df_2022_1['Trimestre'] = 1

df_2022_2['Ano'] = 2022
df_2022_2['Trimestre'] = 2

df_2022_3['Ano'] = 2022
df_2022_3['Trimestre'] = 3

df_2022_4['Ano'] = 2022
df_2022_4['Trimestre'] = 4

# Gerar um código primário unindo as colunas Ano, Trimestre, Código do Município. Essa coluna será usada como chave primária para mesclar as tabelas. Criar uma nova coluna com o nome "UID"
df_2022_1['UID'] = df_2022_1['Ano'].astype(str) + df_2022_1['Trimestre'].astype(str) + df_2022_1['Codigo_Municipio'].astype(str)
df_2022_2['UID'] = df_2022_2['Ano'].astype(str) + df_2022_2['Trimestre'].astype(str) + df_2022_2['Codigo_Municipio'].astype(str)
df_2022_3['UID'] = df_2022_3['Ano'].astype(str) + df_2022_3['Trimestre'].astype(str) + df_2022_3['Codigo_Municipio'].astype(str)
df_2022_4['UID'] = df_2022_4['Ano'].astype(str) + df_2022_4['Trimestre'].astype(str) + df_2022_4['Codigo_Municipio'].astype(str)

# Mesclar as tabelas em uma única tabela
df_2022 = pd.concat([df_2022_1, df_2022_2, df_2022_3, df_2022_4], ignore_index=True)

# Mover as três últimas colunas para o início da tabela concatenada do ano
cols = df_2022.columns.tolist()
cols = cols[-3:] + cols[:-3]
df_2022 = df_2022[cols]

# Salvar a tabela concatenada em um arquivo csv
df_2022.to_csv('C:\\Users\\jobsr\\OneDrive\\Documentos\\GitHub\\ProjetoIntegradorIII\\DATASUS\\Obitos_Procedimento_Municipio\\Tratados\\Obitos_2022.csv', index=False, sep=';', encoding='latin-1')

df_2022.head()

,Ano,Trimestre,UID,Codigo_Municipio,Municipio,Coleta_Material,Diagnostico_Endoscopia,Metodos_Diagnosticos_Especialidades,Consultas_Atendimentos_Acompanhamentos,Tratamentos_Clinicos_Outras_Especialidades,...,Cirurgia_Aparelho_Geniturinario,Cirugia_Mama,Cirurgia_Obstetrica,Cirurgia_Toracica,Cirurgia_Reparadora,Bucomaxilofacial,Outras_Cirurgias,Cirurgia_Oncologia,Processamento_Tecidos_Transplante,Transplante_Orgaos_Tecidos_Celulas
0,2022,1,20221110001,110001,ALTA FLORESTA D'OESTE,0,0,0,0,11,...,0,0,0,0,0,0,0,0,0,0
1,2022,1,20221110002,110002,ARIQUEMES,0,0,0,0,37,...,0,0,0,0,0,0,1,0,0,0
2,2022,1,20221110003,110003,CABIXI,0,0,0,0,4,...,0,0,0,0,0,0,0,0,0,0
3,2022,1,20221110004,110004,CACOAL,0,0,0,1,46,...,0,0,0,2,0,0,3,1,0,0
4,2022,1,20221110005,110005,CEREJEIRAS,0,0,0,0,14,...,0,0,0,1,0,0,0,0,0,0

---

In [34]:
# Mesclar as tabelas de 2019, 2020, 2021 e 2022 em uma única tabela

df = pd.concat([df_2019, df_2020, df_2021, df_2022], ignore_index=True)

# Salvar a tabela concatenada em um arquivo csv

df.to_csv('C:\\Users\\jobsr\\OneDrive\\Documentos\\GitHub\\ProjetoIntegradorIII\\DATASUS\\Obitos_Procedimento_Municipio\\Tratados\\Obitos.csv', index=False, sep=';', encoding='latin-1')

In [35]:
df.head()

,Ano,Trimestre,UID,Codigo_Municipio,Municipio,Coleta_Material,Diagnostico_Endoscopia,Metodos_Diagnosticos_Especialidades,Consultas_Atendimentos_Acompanhamentos,Tratamentos_Clinicos_Outras_Especialidades,...,Cirurgia_Aparelho_Geniturinario,Cirugia_Mama,Cirurgia_Obstetrica,Cirurgia_Toracica,Cirurgia_Reparadora,Bucomaxilofacial,Outras_Cirurgias,Cirurgia_Oncologia,Processamento_Tecidos_Transplante,Transplante_Orgaos_Tecidos_Celulas
0,2019,1,20191110001,110001,ALTA FLORESTA D'OESTE,0,0,0,0,12,...,0,0,0,0,0,0,1,0,0,0.0
1,2019,1,20191110002,110002,ARIQUEMES,0,0,0,0,28,...,0,0,0,1,0,0,3,0,0,0.0
2,2019,1,20191110003,110003,CABIXI,0,0,0,0,3,...,0,0,0,0,1,0,0,0,0,0.0
3,2019,1,20191110004,110004,CACOAL,0,0,0,0,37,...,0,0,0,1,0,0,6,0,0,0.0
4,2019,1,20191110005,110005,CEREJEIRAS,0,0,0,0,6,...,1,0,0,0,0,0,0,0,0,0.0